sudo: required

language: java

services:
  - docker

install:
  - docker build -t sscaling/jmx-prometheus-exporter .

before_script:
  - docker-compose -f test/docker-compose.yml up -d exporter

script:
  - sleep 5
  - cd test
  - docker-compose run query | grep 'jmx_scrape_error 0.0'

